import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { ErrorWrapper } from "./error-wrapper";

export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial - ammar alzaqam",
    template: "%s | ammar-web",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="flex flex-col min-h-screen">
          <Header />
          <div className="grow">
            <ErrorWrapper>{children}</ErrorWrapper>
          </div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
